version: '3.8'

services:

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/prime-numbers
    depends_on:
      - php

  php:
    container_name: php
    build:
      context: ./docker/php/
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/prime-numbers
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
